import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  const router = useRouter();
  const { data } = props;
  console.log(data);

  const navigatePage = () => router.push("/add-to-invoice");
  // total amount of all product items
  const totalAmount = data?.reduce((acc, curr) => acc + curr.total, 0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main__container">
        <div className="invoice__header">
          <div className="invoice__header-logo">
            <h3>Invoices</h3>
            <p>There are total {data?.length} invoices</p>
          </div>
          <div className="invoice__header-logo">
            <h3>Total Amount</h3>
            <p>Total ${totalAmount} of all invoices</p>
          </div>

          <button className="btn" onClick={navigatePage}>
            Add New
          </button>
        </div>

        <div className="invoice__container">
          {/* ======= invoice item =========== */}
          {data?.map((invoice) => (
            <Link href={`/invoices/${invoice.id}`} passRef key={invoice.id}>
              <div className="invoice__item">
                <div>
                  <h5 className="invoice__id">
                    {invoice.id.substr(0, 6).toUpperCase()}
                  </h5>
                </div>

                <div>
                  <h6 className="invoice__client">{invoice.clientName}</h6>
                </div>

                <div>
                  <p className="invoice__created">{invoice.createdAt}</p>
                </div>

                <div>
                  <h3 className="invoice__total">${invoice.total}</h3>
                </div>

                <div>
                  <button
                    className={`${
                      invoice.status === "paid"
                        ? "paid__status"
                        : invoice.status === "pending"
                        ? "pending__status"
                        : "draft__status"
                    }`}
                  >
                    {invoice.status}
                  </button>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  let response = await fetch(
    "https://invoice-delta-gules.vercel.app/api/invoices"
  );
  // extract the data invoice-mamunahmedbd.vercel.app
  let invoices = await response.json();

  return {
    props: {
      data: invoices.map((invoice) => {
        return {
          id: invoice._id,
          clientName: invoice.clientName,
          createdAt: invoice.createdAt,
          total: invoice.total,
          status: invoice.status,
        };
      }),
    },
    // revalidate: 1,
  };
}
// export async function getStaticProps() {
//   let response = await fetch("http://localhost:3000/api/invoices");
//   // extract the data
//   let invoices = await response.json();

//   return {
//     props: {
//       data: invoices.map((invoice) => {
//         return {
//           id: invoice._id,
//           clientName: invoice.clientName,
//           createdAt: invoice.createdAt,
//           total: invoice.total,
//           status: invoice.status,
//         };
//       }),
//     },
//     revalidate: 1,
//   };
// }
